function main()
  monitor = peripheral.wrap( "back" )
  monitor.setTextScale(0.5)
  printSecondFloor()
end

function printSecondFloor()  
  print("floor 2                                         s    =screen")
  print("+-D-+   +--------+                              D    = Door")
  print("|   |   |        |                              p    = pillar")
  print("|   |   | p    p |                              d    = down")
  print("|   |   |        | +--------+                   u    = up")
  print("|   |   |        | |        |                   M    = mystcraft room")
  print("|   |   |        | |        |                   F    = farm")
  print("|   |   | p    p | |        |                   T    = Thaumcraft")
  print("|   |   |        +-+        |")
  print("|   |   |         D    TT   |")
  print("|   |   |        +-+        |")
  print("|   |   | p    p | |        |")
  print("|   |   |        | |        |")
  print("|   |   |        | |        |")
  print("|   |   |        | +-+------+----+")
  print("|   |   +--+  +--+   |           |")
  print("|   |      |DD|      |           |")
  print("|   +-sssss+  +----+ |           |")
  print("|                  | |           |")
  print("|                  +-+           |")
  print("|                   D     FF     |")
  print("+-+  +-ddd--uu-+    D     FF     |")
  print("  |DD|         |   +-+           |")
  print(" ++  ++        |   | |           |")
  print(" |    |        |   | |           |")
  print(" | MM |        |   | |           |")
  print(" |    |        |   | |           |")
  print(" +----+        |   | +-----------+")
  print("               |uuu|")
end

main()